project:
  type: book

book:
  title: "Statistical modelling of competing risks with incomplete data"
  subtitle: "With applications to allogeneic stem cell transplantation"
  author: "Edouard Francis Bonneville"
  chapters:
    - index.qmd
    - chapters/haema-review.qmd
    - chapters/cause-specific-MI.qmd
    - chapters/polverelli-comorbs.qmd
    - chapters/fine-gray-MI.qmd
    - chapters/fine-gray-DGM.qmd
    - chapters/joint-models-DLI.qmd
    - chapters/general-discussion.qmd
    - chapters/references.qmd
    - chapters/samenvatting.qmd
    - chapters/summary.qmd
    - chapters/publications.qmd
    - chapters/dankwoord.qmd
    - chapters/vitae.qmd

format:
  pdf:
    documentclass: scrbook
    pdf-engine: pdflatex
    latex-clean: true # Set to false for index.log file to check for issues
    keep-tex: false
    classoption:
      - paper=portrait
      - paper=240mm:170mm
      - twoside=true
      - parskip=half+
      - open=right
      - fontsize=10pt
      - pagesize=false # set to auto if not sending to printers
      - BCOR=15mm # Binding correction (Ridderprint needs min 20mm for binding)
      - DIV=14 # Makes text area bigger (DIV=calc is default, outputs 10 here)
      - headinclude=true # true or else upper margin too small
      - footinclude=false # false or else bottom margin too large
      - headsepline=on # Line in headers
    link-citations: true
    toc-depth: 2
    lot: false # Both set to false to save printing costs
    lof: false
    latex-auto-install: true
    include-in-header:
      - tex/preamble-global.tex # (!) Make similar globals for html later
    template-partials:
      - tex/before-body.tex
  html:
    theme: cosmo
    fig-height: 10
    toc: true
    toc-depth: 2
    number-depth: 4
    mainfont: Roboto #Fira Sans

bibliography: thesis-refs-all.bib
csl: journal-of-the-royal-statistical-society.csl
number-depth: 2

# Defense settings to populate first few pages
proefschrift:
  day: "woensdag 2 juli 2025"
  time: "11:30"
  birthplace: "Madrid, Spanje"
  birthyear: "1995"
  rector: "prof. dr. ir. H. Bijl"
committee:
  - name: Prof. dr. J. Wallinga
  - name: Prof. dr. J. Beyersmann
    affiliation: Universität Ulm, DE
  - name: Prof. dr. S. van Buuren
    affiliation: Universiteit Utrecht, NL
  - name: Dr. S. Iacobelli
    affiliation: Sapienza Università di Roma, IT
