project:
  type: book

book:
  title: "Advances in competing risks and missing data"
  subtitle: "With applications to allogeneic stem cell transplantation"
  author: "Edouard F Bonneville"
  chapters:
    - index.qmd
    - general-introduction.qmd
    - chapters/haema-review.qmd # add broader sections/parts after, if necessary
    - chapters/cause-specific-MI.qmd
    - chapters/fine-gray-MI.qmd
    - chapters/fine-gray-DGM.qmd
    - chapters/joint-models-DLI.qmd
    - general-discussion.qmd
    - summary.qmd # after this: CV, acknowledegments and other tings

format:
  html:
    theme: cosmo
    fig-height: 10
  pdf:
    documentclass: scrreprt #scrbook or book
    link-citations: true
    citeproc: false # recommended by filters
    toc-depth: 2
    lot: true
    lof: true
    latex-auto-install: true
    keep-tex: true
    include-in-header:
      - tex/preamble-global.tex # make similar globals for markdown?
    filters:
      - section-bibliographies

bibliography: thesis-refs-all.bib
csl: journal-of-the-royal-statistical-society.csl
number-depth: 2
