project:
  type: book

book:
  title: "Statistical modelling of competing risks with incomplete data"
  subtitle: "With applications to allogeneic stem cell transplantation"
  author: "Edouard Francis Bonneville"
  chapters:
    - index.qmd
    - chapters/haema-review.qmd
    - chapters/cause-specific-MI.qmd
    - chapters/polverelli-comorbs.qmd
    - chapters/fine-gray-MI.qmd
    - chapters/fine-gray-DGM.qmd
    - chapters/joint-models-DLI.qmd
    - chapters/general-discussion.qmd
    - chapters/references.qmd
    - chapters/summary.qmd
    - chapters/publications.qmd
    - chapters/dankwoord.qmd
    - chapters/vitae.qmd

format:
  html:
    theme: cosmo
    fig-height: 10
  pdf:
    documentclass: scrbook
    classoption:
      - paper=portrait
      - paper=24cm:17cm
      - twoside=true
      - open=right
      - fontsize=10pt
      - pagesize={{< meta print >}}
    mathspec: true # Important for boldsymbols
    link-citations: true
    toc-depth: 2
    lot: false # (!) Remove both of these to save printing costs?
    lof: false
    latex-auto-install: true
    include-in-header:
      - tex/preamble-global.tex # make similar globals for html?
    template-partials:
      - tex/before-body.tex
    keep-tex: true

bibliography: thesis-refs-all.bib
csl: journal-of-the-royal-statistical-society.csl
number-depth: 2

# Other mini tings
proefschrift:
  day: "[weekday] [dag] [maand] 2025"
  time: "xx:xx"
  birthplace: "Madrid, Spanje"
  birthyear: "1995"
  rector: "prof. dr. Iemand"

committee:
  - name: Prof. dr. Jacco Wallinga
    affiliation:
      - Leiden University Medical Center, NL
      - RIVM, NL
  - name: Prof. dr. Jan Beyersmann
    affiliation: University of Ulm, DE
  - name: Prof. dr. Stef van Buuren
    affiliation: University of Utrecht, NL
  - name: Dr. Simona Iacobelli
    affiliation: Sapienza University of Rome, IT

print: false

# quarto check in command line checks a bunch of locations
# tinytex::tinytex_root()
# https://ctan.org/tex-archive/info/examples/KOMA-Script-6
