project:
  type: book

book:
  title: "Statistical modelling of competing risks with incomplete data"
  subtitle: "With applications to allogeneic stem cell transplantation"
  author: "Edouard Francis Bonneville"
  chapters:
    - index.qmd
    - chapters/haema-review.qmd
    - chapters/cause-specific-MI.qmd
    - chapters/polverelli-comorbs.qmd
    - chapters/fine-gray-MI.qmd
    - chapters/fine-gray-DGM.qmd
    - chapters/joint-models-DLI.qmd
    - chapters/general-discussion.qmd
    - chapters/references.qmd
    - chapters/samenvatting.qmd
    - chapters/summary.qmd
    - chapters/publications.qmd
    - chapters/dankwoord.qmd
    - chapters/vitae.qmd

format:
  pdf:
    documentclass: scrbook
    pdf-engine: pdflatex
    latex-clean: false # Keep the index.log file to check for issues e.g. overfullness
    keep-tex: true
    classoption:
      - paper=portrait
      - paper=240mm:170mm
      - twoside=true
      - open=right
      - fontsize=10pt
      - pagesize=false # set to auto if not sending to printers
      - BCOR=15mm # 9mm Binding correction (Ridderpr. needs min 20mm for binding)
      - DIV=14 # Makes text area bigger (DIV=calc is default, outputs 10 here)
      - headinclude=true # true or else upper margin too small
      - footinclude=false # false or else bottom margin too large
      - headsepline=on # Line in headers
    link-citations: true
    toc-depth: 2
    lot: false # Is set to false to save printing costs
    lof: false
    latex-auto-install: true
    include-in-header:
      - tex/preamble-global.tex # (!) make similar globals for html later
    template-partials:
      - tex/before-body.tex
  html:
    theme: cosmo
    fig-height: 10

bibliography: thesis-refs-all.bib
csl: journal-of-the-royal-statistical-society.csl
number-depth: 2

# Defense setting to populate first few pages
proefschrift:
  day: "[weekdag] [dag] [maand] 2025"
  time: "xx:xx"
  birthplace: "Madrid, Spanje"
  birthyear: "1995"
  rector: "Prof. dr. ir. Hester Bijl"
committee:
  - name: Prof. dr. Jacco Wallinga
    affiliation:
      - Leids Universitair Medisch Centrum, NL
      - Rijksinstituut voor Volksgezondheid en Milieu, NL
  - name: Prof. dr. Jan Beyersmann
    affiliation: Universität Ulm, DE
  - name: Prof. dr. Stef van Buuren
    affiliation: Universiteit Utrecht, NL
  - name: Dr. Simona Iacobelli
    affiliation: Sapienza Università di Roma, IT
