project:
  type: book

book:
  title: "Advances in competing risks and missing data"
  subtitle: "With applications to allogeneic stem cell transplantation"
  author: "Edouard F Bonneville"
  chapters:
    - index.qmd
    - chapters/haema-review.qmd
    - chapters/cause-specific-MI.qmd
    - chapters/polverelli-comorbs.qmd
    - chapters/fine-gray-MI.qmd
    - chapters/fine-gray-DGM.qmd
    - chapters/joint-models-DLI.qmd
    - chapters/general-discussion.qmd
    - chapters/references.qmd
    - chapters/summary.qmd
    - chapters/publications.qmd
    - chapters/dankwoord.qmd
    - chapters/vitae.qmd

format:
  html:
    theme: cosmo
    fig-height: 10
  pdf:
    documentclass: scrreprt #, scrbook or book
    mathspec: true # important for boldsymbols
    link-citations: true
    #citeproc: false # recommended by filters, bib per chapter
    toc-depth: 2
    lot: true
    lof: true
    latex-auto-install: true
    include-in-header:
      - tex/preamble-global.tex # make similar globals for markdown?
    keep-tex: true

bibliography: thesis-refs-all.bib
csl: journal-of-the-royal-statistical-society.csl
number-depth: 2
