# List of publications {.unnumbered}

<!-- footnotes? -->

\blfootnote{$^\dagger$These authors contributed equally to this work and share first authorship.}

- **Bonneville, E. F.**, Resche-Rigon, M., Schetelig, J., Putter, H., de Wreede, L.C. (2022) Multiple imputation for cause-specific Cox models: Assessing methods for estimation and prediction. *Statistical Methods in Medical Research*, 31, 1860–1880. SAGE Publications Ltd STM. DOI: [10.1177/09622802221102623](https://doi.org/10.1177/09622802221102623).

- **Bonneville, E. F.**, Schetelig, J., Putter, H., de Wreede, L.C. (2023) Handling missing covariate data in clinical studies in haematology. *Best Practice & Research Clinical Haematology*, 36, 101477. DOI: [10.1016/j.beha.2023.101477](https://doi.org/10.1016/j.beha.2023.101477).

- Koster, E.A.S.$^\dagger$, **Bonneville, E.F.**$^\dagger$, von dem Borne, P.A., van Balen, P., Marijt, E.W.A., Tjon, J.M.L., Snijders, T.J.F., van Lammeren, D., Veelken, H., Putter, H., Falkenburg, J.H.F., Halkes, C.J.M., de Wreede, L.C. (2023) Joint models quantify associations between immune cell kinetics and allo-immunological events after allogeneic stem cell transplantation and subsequent donor lymphocyte infusion. *Frontiers in Immunology*, 14. Frontiers. DOI: [10.3389/fimmu.2023.1208814](https://doi.org/10.3389/fimmu.2023.1208814).

- Polverelli, N.$^\dagger$, **Bonneville, E.F.**$^\dagger$, de Wreede, L.C., Koster, L., Kröger, N.M., Schroeder, T., Peffault de Latour, R., Passweg, J., Sockel, K., Broers, A.E.C., Clark, A., Dreger, P., Blaise, D., Yakoub-Agha, I., Petersen, S.L., Finke, J., Chevallier, P., Helbig, G., Rabitsch, W., Sammassimo, S., Arcaini, L., Russo, D., Drozd-Sokolowska, J., Raj, K., Robin, M., Battipaglia, G., Czerw, T., Hernández-Boluda, J.C., McLornan, D.P. (2024) Impact of comorbidities and body mass index on the outcomes of allogeneic hematopoietic cell transplantation in myelofibrosis: A study on behalf of the Chronic Malignancies Working Party of EBMT. *American Journal of Hematology*, 99, 993—996. DOI: [https://doi.org/10.1002/ajh.27262](https://doi.org/10.1002/ajh.27262)

- **Bonneville, E. F.**, de Wreede, L. C. and Putter, H. (2024) Why you should avoid using multiple Fine–Gray models: Insights from (attempts at) simulating proportional subdistribution hazards data. *Journal of the Royal Statistical Society Series A: Statistics in Society*, qnae056. DOI: [10.1093/jrsssa/qnae056](https://doi.org/10.1093/jrsssa/qnae056

- **Bonneville, E. F.**, Beyersmann, J., Keogh, R. H., Bartlett, J.W., Morris, T.P., Polverelli, N., de Wreede, L.C., Putter, H. (2024) Multiple imputation of missing covariates when using the Fine--Gray model. *arXiv preprint* arXiv:2405.16602. DOI: [10.48550/arXiv.2405.16602](
https://doi.org/10.48550/arXiv.2405.16602).
