# Curriculum vitae {.unnumbered}

Edouard Francis Bonneville was born on July 20^th^ 1995 in Madrid (Spain). After completing his secondary education in Colomiers (France) in 2013, he pursued a BSc in Psychology at the University of Bristol (United Kingdom). In 2016, he moved to Leiden (the Netherlands) for the MSc Statistical Science for the Life and Behavioural Sciences, which is now known under the name 'Statistics and Data Science'. As part of his master thesis, he spent three months at the RIVM Dutch National Institute for Public Health and the Environment working on a Bayesian approach for forecasting infection disease epidemics. 

In 2019, he started his PhD in Biostatistics at the Department of Biomedical Data Sciences at Leiden University Medical Center (LUMC, the Netherlands) under the supervision of Dr. Liesbeth de Wreede and Prof. Dr. Hein Putter. The results of his research, which focused on statistical methodology at the intersection of competing risks and missing data, are outlined in this thesis. During his PhD programme, he visited both the Department of Medical Statistics at the London School of Hygiene \& Tropical Medicine (United Kingdom), and the Institute of Statistics at Ulm University (Germany). Alongside his PhD, he was part of the LUMC Association for PhD Candidates (LAP) board for two years, during which he was treasurer and co-organised several events.

Between 2022 and 2024, he also worked part-time as a study statistician for the European Society for Bone and Marrow Transplantation (EBMT). Finally, he has served as a reviewer for the journals *Statistics in Medicine*, *Statistical Methods in Medical Research*, *BMC Medical Research Methodology*, *Biometrical Journal* and *Journal of Computational and Graphical Statistics*.
